### ISSUE TITLE
(not an issue) could you upload a CIA release?

### ISSUE THREAD

**Issue by placeboyue** [cgao0520/NomadSwan#1]
I'm a total noob when it comes to compiling stuff from a github repo, and this is the only wonderswan emulator besides medafen for 3DS, which works slow AF on O3DS so i really wanna try yours!

hope you read this before covid and global warming kills us all, cheers

**Comment by cgao0520** [comment]
Hi there,

I like your humor, and I’ve attached the previously built 3dsx file for you. Let me know if you have any problem using it, enjoy!

To build the code, you will need devkitARM r43, which is pretty much old version, I haven’t had time to update the code to work with latest tool chain.

Best,
Vincent

**Comment by placeboyue** [comment]
I'm not seeing an attachment anywhere. 
I'm pretty sure it's me now knowing where to find it, this is so embarrasing lol.
Thanks for being so eager to help out

**Comment by cgao0520** [comment]
Try this out: [NomadSwan binary](http://www2.cs.uregina.ca/~gao266/downloads/NomadSwan_bin.zip)
I replied previously by email and it does't support attaching files. But it shall be fine now.

**Comment by cgao0520** [comment]
Close as it is not an actual issue and resolved as well.
